name: Test

on:
  pull_request: { }
  push:
    branches:
      - main
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build
        run: |
          sudo apt-get install libasound2-dev
          make build

      - name: Test
        run: |
          make test
          make vet

  e2e_test:
    # I tried for quite a while to get this working on Ubuntu (both VM and docker), but all the alsa
    # stuff that makes midi work on Linux isn't in the runners. snd-virmidi, snd-dummy,
    # snd-aloop, snd-seq, etc. are all unavailable
    runs-on: macos-latest
    name: E2E Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: E2E Test
        run: |
          cd test/e2e/
          pip install -r requirements.txt

          python -m unittest main.py
